### ISSUE TITLE
Reflections on tile ordering by most recent commit

### ISSUE THREAD

**Issue by vincentvanhees** [research-software-directory/research-software-directory#148]
The RSD software tiles seem to be ordered by most recent commit. I doubt this is ideal, because it will put software that is very actively maintained constantly at the top of the list, e.g. currently Kernel tuner and GGIR.

Although it is nice for those software, I think it is better for both developers and RSD visitors if  the sorting algorithm could be less strict about this, because:
- We want to promote software that was developed in all projects that ended in the last 12 months and is not actively maintained anymore. Sorting by recent commit will disadvantage those software, while they are probably most in need for new users and developers.
- More recent commits is not necessarily a good thing, it could also indicate that the software is not in a mature state yet and someone is working hard to fix all the bugs.

**Comment by jspaaks** [comment]
Hi Vincent, 
thanks for the suggestion. Note that the site does allow you to have 2 other ways for sorting (although they are curently broken, d'oh).

I don't think there is an ideal way of sorting (it's basically the same problem as trying to determine software impact, which nobody knows how to do). But anyway, we chose to have a default ranking based on some measure of 'activity', because we believe this is a minimal requirement for other people to even consider adopting a new software package.

With regard to discovering software, you should keep in mind that the index page is not the main portal for people to find us, instead we should optimize for being found through search engines (basically, Google). The index page is more aimed at people who are interested in the organization, and want to get a quick overview. As they are not immediately looking for a software package to solve a particular problem, the precise type of sorting and filtering we do is not critically important IMHO. Naturally, it will become more important as the number of items in the Research Software Directory grows.

Having said that, perhaps we could consider replacing one of the existing sorting algorithms with the one you're describing, but I'm struggling a little bit with formalizing what you propose, e.g from your description, the software should:

1. result from a project whose end date was somewhere in the last N months
1. should have no more than a few commits since the project ended

But how do we differentiate between the set of software packages that meet these criteria?

**Comment by vincentvanhees** [comment]
Hi Jurriaan,
I understand that there is not an easy generic solution, but to me this seems like an important area for research and development in order to turn the RSD into a world class technology.

With enough time investment anyone can build a webpage that lists research software, but what could set it apart from potential alternatives is embedded expertise on how to best sort software to optimize the visitor's rating of the institute to which the RSD is linked and at the same time make visitors who are specifically looking for something find what they need. Yes, google should partly take care of that, but it would be very valuable if the RSD itself is also as easy as possible to navigate for a visitor.

The sorting functionality is especially important for the use case 'portfolio display'. Here, I consider the manual labelling of 'gems' part of the sorting functionality. The 'gem' labels feel subjective to me as some of them hardly have mentions or for whom it is not clear at all what NLeSC contributed and what external parties did. It would be powerful if the RSD could identify the 'gems' itself more objectively, with more clarity about contributions, and with less human involvement. Further, I think it would help if we split the gems up in 'featured new software we recommend you to try' and 'established software from the past with high impact we are proud of'. The first category has many recent commits but few mentions, while the second category may have many mentions but only few recent commits. To me the latter is a sign of maturity, because usually the commits stop when a project is finished.
Vincent

**Comment by jspaaks** [comment]
Closing this issue, feel free to reopen if necessary.
