### ISSUE TITLE
Add EOSCpilot projects to the list

### ISSUE THREAD

**Issue by arnikz** [research-software-directory/research-software-directory#161]
I'd like to mention a software (re)used in the EOSCpilot-LOFAR project but it's not in the list.

**Comment by jspaaks** [comment]
OK, so summarizing our offline discussion:
you have an existing product page on the Research Software Directory (here: https://www.research-software.nl/software/linked-data-platform-for-plant-breeding-genomics), to which you want to add a new "related project" namely the ``EOSCpilot for LOFAR``, but you don't see an entry by that name in the dropdown you get on the Admin page to the Research Software Directory.

The reason you don't see it is because there is no project description for ``EOSCpilot for LOFAR`` on https://www.esciencecenter.nl/projects yet. The contents of https://www.esciencecenter.nl/projects are harvested overnight, and end up as selectable items in the dropdown. So, what you need to do is supply Sacha with a project description for ``EOSCpilot for LOFAR``, which she can then enter in the content management system that controls https://www.esciencecenter.nl/projects.
