### ISSUE TITLE
redirecting links does not work properly

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/research-software-directory#172]
Most links are supposed to open in a new page  / new widow. That happens, but the current window *also* opens the link.
so, currently
1. click on a link
2. have 2 tabs/windows with the link

expected:
1. click on a link
2. have it open in a new tab, and leave the current page as is.

this happens for at least this link:
https://research-software.nl/software/ggir unfold the "Conference paper" dropdown, and click on a publication

**Comment by Tommos0** [comment]
- Works as expected in Chrome
- Reproduced in Firefox

I think it's caused by this line (part of outbound link click reporting to Google Analytics): https://github.com/research-software-directory/frontend/blob/4ed56c0562baaf656e7901808c9bcae09cb848ee/templates/layout_template.html#L25

At least, when `target=_blank`, we should update window.location. Also, perhaps we should track both events separately:
- event type 1: Link opened in new tab
- event type 2: External link opened  in current window.

Or either of:
- Make sure all outbound links have `target=_blank`.
- Don't track outbound links at all (if this is not useful information).

**Comment by jspaaks** [comment]
What if we leave the callback empty? It seems that we would still have outgoing ``href`` stored in ``event_label``, assuming that shows up in analytics.google.com. 

It seems to me that setting ``document.location`` in a GoogleAnalytics script is not where you expected that work to be done, right?
