### ISSUE TITLE
restructuring proposal

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#186]
This issue records some changes I propose after setting up 2 new instances of the RSD
- CCS Amsterdam: https://ec2-52-36-66-25.us-west-2.compute.amazonaws.com/
- PROCESS: https://ec2-34-221-149-172.us-west-2.compute.amazonaws.com/

1. remove submodules (too counterintuitive, and as it turns out, does not help with releasing the full stack on Zenodo. We should come up with a different mechanism for this.)
1. have sibling repositories instead of hierarchy
1. docker-compose only? (I'd forgotten Ansible playbooks were used in production, but this turned out not to be a problem at all, AFAICT the new instances run like normal. This raises the question: do we really need Ansible? Ditching Ansible limits the number of technologies that people need to learn; limits the number of sources of error; limits the documentation we need to write and maintain)
1. remove unused repositories from this organization (``stack``, ``pymongal``, ``readthedocs``, ``schema-nlesc``)
1. rename repositories (prepending ``rsd-`` helps people forking into their own orgs that have existing code)
1. rename ``tasks-nlesc`` to ``rsd-tasks``
1. rename ``research-software-directory`` to ``rsd-main``

An example setup of some of these changes is here https://github.com/process-project.

I'd be interested in your opinions on this @Tommos0 and @sverhoeven.

**Comment by sverhoeven** [comment]
1. Agreed, the scripts will need some way to specify the versions of the other repos
2. You will always have a starting point which is the main repo, I can not tell what a siblings layout would look like. A monorepo will make releasing/deployment easier, but make testing and indepent work harder.
3. The Ansible scripts setup a production machine for running the Docker containers. So both Ansible and docker compose are required
4. I the information or equivalent in those repos is available somewhere else then remove them otherwise archive with clear deprecation warning.
5. Agreed
6. Agreed
7. Please don't, I would keep it named `research-software-directory`, this what I expect the main repo to be called.

**Comment by jspaaks** [comment]
A monorepo setup would solve or avoid my items 1, part of 2, 5, 6, and 7 above. Let's look at the downside though:
 
I don't expect independent work would be made more difficult by a monorepo setup. I say this after having tried to do independent work for 2 new rsd instances. Figuring out what changes were in which location was a pain: you're dealing with upstream and origin; multiple branches in upstream and origin; local changes on your local machine and amazon machine. If we can cut down on the cognitive load this imposes I think it's worth a try.

Moreover, I don;t think there will be much truly independent work, i.e. work that only relates to one repo, e.g. only to ``frontend``; for that the parts are too tightly coupled.

@sverhoeven Regarding testing, will a monorepo setup make things intrinsically more difficult or do you mean it will make things slower? The latter is not so much of a problem I think. 

I'm interested to hear your thoughts on this.

**Comment by sverhoeven** [comment]
All the tests of the separate repos will need to be run together in the monorepo. Making the test config more complex, but doable.
