### ISSUE TITLE
Provide short(ened) URLs to all software in RSD

### ISSUE THREAD

**Issue by arnikz** [research-software-directory/research-software-directory#281]
It does not make much sense to duplicate "software" in the URL unless there are plans to provide URLs of associated research data as well.

Proposition:
https://research-software.nl/software/XXX -> https://research-software.nl/XXX

or

https://research-software.nl/data/ as we've also got some research software linked to data(sets) (e.g., currently as "Document" in the mentions of [this](https://research-software.nl/software/qtl-tableminer) software)

**Comment by jspaaks** [comment]
This would at least affect some of the routes in https://github.com/research-software-directory/research-software-directory/blob/a6a633dd076d1e05d6b028764ee9bf5a26c7bc8c/frontend/app/application.py

i'm not in favor of also including data, I'd rather point to a place where there is data, such as Zenodo. It would be helpful if Zotero had a 'data' type, or alternatively we could expand the schema such that people can stick their own labels on items that they link to. So instead of your 'Document' type, users could choose from either a dropdown enum with strings that we determine ourselves (for example 'Data set' or something), or have a free text field.

**Comment by arnikz** [comment]
In principle, one could have both the long (original) and short URLs (e.g., adding URL rewrite rule/redirect).

WRT Zenodo: yes, it supports `Dataset` type (see an example [here](https://zenodo.org/record/1215044/export/schemaorg_jsonld#.XNF35qZS_wg) in JSON-LD).

**Comment by jspaaks** [comment]
OK, but ``type: dataset`` in the extra field is too fragile to depend on. Plus it does not automatically result in your data set showing up as ``data set``: it would still show as ``document``. Anyway, bit of a side quest to this issue.

**Comment by Tommos0** [comment]
We also have for instance `research-software.nl/about`. I like having `/software` in between so that we have a clear namespace for software only.

**Comment by arnikz** [comment]
As mentioned earlier, you could keep the namespace `/software` and also add a shorthand path that points to it.  My "inspiration" came from https://bio.tools/ (directly followed by software name) while updating the records.

**Comment by Tommos0** [comment]
We could do `/s/<slug>` ? I'm a bit afraid of namespace clashes in the future. What if someone names his tool `about` etc.

**Comment by jspaaks** [comment]
closing because of anticipated namespace clashes
