### ISSUE TITLE
Citation block disappears for some versions

### ISSUE THREAD

**Issue by c-martinez** [research-software-directory/research-software-directory#291]
On some items (e.g. Xenon) some versions (3.0.0) citation block is visible. But when selecting a different version (e.g. 2.6.0, 2.5.0, 2.4.1) the block disappears.

**Comment by jspaaks** [comment]
Indeed this is partly due to https://github.com/research-software-directory/research-software-directory/issues/288 which is hopefully solved by https://github.com/research-software-directory/research-software-directory/pull/290, and partly due to incomplete or incorrect citation metadata in particular releases.

for example, using the online cffconvert
- 2.6.0: https://us-central1-cffconvert.cloudfunctions.net/cffconvert?url=https://github.com/xenon-middleware/xenon/tree/2.6.0&validate
- 3.0.0: https://us-central1-cffconvert.cloudfunctions.net/cffconvert?url=https://github.com/xenon-middleware/xenon/tree/3.0.0&validate

For me, the citation block does not disappear BTW, just the BibTeX dropdown part of it. There are some entries that currently do no show a citation block at all, like https://research-software.nl/software/muscle3, but that is not the behavior you are referring to in this issue, correct?

**Comment by c-martinez** [comment]
Yes, it is only the export to bibtex part which disappears.

**Comment by jspaaks** [comment]
FYI https://doi.org/10.5281/zenodo.1477864 (slide 18) has 3 possible behaviors. Closing this one.

**Comment by c-martinez** [comment]
Hmmm... But is it not possible to generate bibtex information from zenodo (in the cases where CFF file is not available) ?

**Comment by jspaaks** [comment]
Definitely possible. Not implementing that has been a design choice on my part. I prefer to offer one good way to supply this information, which probably covers >95% of cases. I don't think we should spend time fixing problems that others can easily avoid by just following what we indentified as a good practice.

**Comment by c-martinez** [comment]
It kind of pushes people to follow our recommendations, but fair enough :-)

**Comment by jspaaks** [comment]
Agreed, pushy, but we are in a somewhat unique position because we have experience with what works and what doesn't. That is how best practices arise, after all. 

To clarify, an early version of the Research Software Directory did use Zenodo's BibTeX download option. The trouble with that, as we discovered, is that the quality of the metadata is terrible ([example](https://zenodo.org/record/1064516/export/hx#.XTl9WPxS9tc)), so providing yet another platform for such ugly, incorrect metadata did not seem like a good idea (basically, you're just spreading garbage around).

This meant the nature of the problem changed from being a technical problem (getting the data from some API or whatever, and then doing the conversion) to a business process problem (how do you get your people to supply metadata that isn't blatantly wrong, and have them do so unsupervised and continuously).

I deemed it unrealistic that people would manually update/correct their metadata on Zenodo when making a release on GitHub (only notable exceptions to that rule have been @sverhoeven and @arnikz who do this quite diligently; most of our colleagues don't). That got us to needing good quality metadata on GitHub (which is a good idea anyway). So, in practice that meant people needed to add a ``.zenodo.json`` file to their repositories.

At that point we had a few options:
- tell people to edit the ``.zenodo.json`` file directly. Big downside to that is that mistakes will not manifest themselves as such, the release will just have incorrect metadata associated with it, but still be published and visible until the end of time. Other downsides to ``.zenodo.json``: it is quite limited in what can be recorded, it was mostly undocumented at the time, and it was really only meant for Zenodo's internal use to be read by machines, not humans.
- alternatively we could use CodeMeta or CITATION.cff files, and then use a converter like [``cffconvert``](https://pypi.org/project/cffconvert)  to generate a ``.zenodo.json``. Users find CITATION.cff easier to write and read than CodeMeta, hence we chose that.

Naturally, other instances of the Research Software Directory are free to make their own choices regarding enabling citation. As long as it works from a technical point of view as well as from a business process point of view, I'm happy.
