### ISSUE TITLE
check that on resize, text wrapping looks ok; make it responsive

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#596]
groomed from #594

**Comment by sverhoeven** [comment]
Checked responsiveness on width of 2160p,1440p, 1080p and 400p. Also checked mobile potrait/landscape mode.

The projects page render correctly on  all widths and mobile rotations.

The ABC-MUSE project page had a couple of problems:

1. Text on team section on narrow screen is centered while on wider screen it is aligned left. I expected it to stay aligned left
1. Main figure on narrow screens get distorted by not resizing with aspect ratio in mind
![localhost_projects_764 (2)](https://user-images.githubusercontent.com/1713488/98825324-a3352300-2434-11eb-8077-c8e6d8067c4f.png)

**Comment by cwmeijer** [comment]
This issue is not quite done because there is another issue with the responsiveness that needs fixing. It is not breaking the page but it certainly doesn't look nice.
When I'm using my iPad (my virtual one of course) and scroll down to partners, I get to see humongous logos. This is because we styled the sidebar as a relatively narrow column, but when viewing it on a tablet or phone, the sidebar gets rendered in full screen width. See for instance:

![image](https://user-images.githubusercontent.com/6087314/99383656-75d1f480-28ce-11eb-94b5-e6633f55a5bb.png)

- When using the iPad in landscape mode, the sidebar gets rendered on the side, like intended.
- We get the same problem when using a smartphone in landscape mode. 
- When using a smartphone in portrait mode, it is a lot better but still ugly, see:


![image](https://user-images.githubusercontent.com/6087314/99384149-4a033e80-28cf-11eb-8c72-082449dd642a.png)


Concluding: This problem arises for tablets in portrait mode, and smartphones.

**Comment by jspaaks** [comment]
can we add a `max-width` on these images, and set it equal to whatever 80% of the sidebar width is in pixels?

**Comment by jspaaks** [comment]
@cwmeijer if you're working on this, can you assign yourself please?

**Comment by jspaaks** [comment]
PR was merged, closing
