### ISSUE TITLE
add "Topic" filter list to project index page

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#655]
Refs #649

**Comment by eriktks** [comment]
Note: the topics per project have already been scraped from the corporate website by the corporate scraper from PR #609  but have not yet been added to the RSD because there was no place for them in the project scheme at the backend

**Comment by cwmeijer** [comment]
Make a good plan together with team, for this one before working on it (grooming).

**Comment by sverhoeven** [comment]
In the project schema we currently have a [tags field with technological terms](https://github.com/research-software-directory/research-software-directory/blob/540efd0f5be2a21dd8fe0a15344199002102576e/backend/schemas/project.json#L154-L174). 
In the [mockup](https://github.com/research-software-directory/research-software-directory/issues/649) there are 2 filters: one for scientific topics and one for technology.

To make the mockup a reality I see 2 ways:
1. We add scientific topic terms to the tags enum 
    * on the project index page split it in 2 filters
    * on the project page we show the tags as is
2. We add a topics field to the project schema
    * on the index page we add both filters working on their own field
    * on the project page we show both fields as single collection of tags
    * optionally rename tags field to technology tags

I prefer the way 2 because it keeps things simpler. As way 1 would need the 2 enums also, but in code instead of schema.

**Comment by sverhoeven** [comment]
We decided to go with option 2 with the team

**Comment by jspaaks** [comment]
Refs #652 (enum items for topics)

**Comment by jspaaks** [comment]
PR was merged, closing
