### ISSUE TITLE
github repo of the software moved, but zenodo ofcourse points to the old repo

### ISSUE THREAD

**Issue by jiskattema** [research-software-directory/research-software-directory#787]
Not sure this is an RSD bug, but it is related to the metadata.
The tool ```psrdada-python``` has moved from the repo used during developement to here ```https://github.com/TRASAL/psrdada-python``` from here ```https://github.com/AA-ALERT/psrdada-python/```.
However, zenodo does not know about this, and keeps pointing to the (now broken) old repo.

Can i update Zenodo? What is the best way forward?

**Comment by jspaaks** [comment]
Hi Jisk, thanks for taking the time to create this issue. It isn't a issue with the Research Software Directory, but here are some pointers:

The entry on Zenodo https://zenodo.org/record/3944609 has metadata that points to a repository which has moved since the deposition was created. If you own the deposition, there will be a button `edit` in Zenodo's top right corner, then scroll down to the Related Identifiers part. You can update the URL to point to the new place, or you can choose to do nothing, since the GitHub URL will redirect automatically to the new place. This will keep working until someone recreates repo https://github.com/AA-ALERT/psrdada-python.

Hope this helps. Feel free to reopen if need be
